version: '3.1'

services:
  #front:
    #container_name: luciole-front-prod
    #build:
      #context: ./luciole
      #target: prod
    #ports:
      #- 80:80

  #back:
    #container_name: luciole-back-prod
    #build:
      #context: ./luciole-back
      #target: prod
    #ports:
      #- 3000:3000

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
